language: generic
sudo: required
services:
  - docker

env:
    matrix:
        - DEBOOTSTRAP_FORCE_GPG_CHECK=no DIST=wheezy
        - DEBOOTSTRAP_FORCE_GPG_CHECK=no DIST=jessie
        - DEBOOTSTRAP_FORCE_GPG_CHECK=no DIST=stretch

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq debootstrap
script:
    - make image && make test
after_success:
  - if [ "$TRAVIS_REPO_SLUG" = nantesmetropole/docker-debian -a "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = false ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make push;
    fi
